import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
  },
  preview: {
    flex: 1,
  },
  status: {
    color: '#fff',
    textAlign: 'center',
    padding: 24,
  },
  errorBanner: {
    position: 'absolute',
    top: 60,
    alignSelf: 'center',
    color: '#f66',
    paddingHorizontal: 16,
  },
  timer: {
    position: 'absolute',
    top: 60,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  timerText: {
    color: '#fff',
    fontVariant: ['tabular-nums'],
    fontSize: 18,
  },
  recordButton: {
    position: 'absolute',
    bottom: 40,
    alignSelf: 'center',
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 4,
    borderColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#e33',
  },
  toast: {
    position: 'absolute',
    bottom: 130,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1c1c1e',
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
    maxWidth: '88%',
    gap: 14,
  },
  toastText: {
    color: '#fff',
    fontSize: 13,
    lineHeight: 18,
    flexShrink: 1,
  },
  toastClose: {
    color: '#8e8e93',
    fontSize: 15,
    fontWeight: '600',
  },
  healthBanner: {
    position: 'absolute',
    top: 100,
    alignSelf: 'center',
    backgroundColor: 'rgba(200,40,40,0.9)',
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    maxWidth: '85%',
  },
  healthText: {
    color: '#fff',
    fontSize: 14,
    textAlign: 'center',
  },
  debugEntry: {
    position: 'absolute',
    top: 60,
    right: 16,
  },
  debugEntryText: {
    color: 'rgba(255,255,255,0.55)',
    fontSize: 13,
  },
  stopIcon: {
    width: 28,
    height: 28,
    borderRadius: 4,
    backgroundColor: '#e33',
  },
})
