import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#111',
    paddingTop: 60,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  headerSide: { width: 32, alignItems: 'center' },
  headerTitle: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 20,
  },
  // Only inside headerRow, fills the space between the side slots.
  headerTitleRow: { flex: 1 },
  gearGlyph: { color: '#4a90d9', fontSize: 32, marginBottom: 8 },
  error: { color: '#f66', textAlign: 'center', padding: 8 },
  sheet: {
    flex: 1,
    backgroundColor: '#111',
    paddingTop: 24,
  },
  settingsCard: {
    borderRadius: 10,
    marginHorizontal: 12,
    marginBottom: 8,
    padding: 12,
  },
  settingsLabel: { color: '#ddd', fontSize: 13, marginBottom: 8 },
  settingsNote: { color: '#777', fontSize: 11, marginTop: 8, lineHeight: 15 },
  segmentRow: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    marginBottom: 20,
  },
  segment: {
    flex: 1,
    borderColor: '#444',
    borderWidth: 1,
    borderRadius: 6,
    paddingVertical: 6,
    alignItems: 'center',
  },
  segmentActive: { backgroundColor: '#4a90d9', borderColor: '#4a90d9' },
  segmentText: { color: '#aaa', fontSize: 13 },
  segmentTextActive: { color: '#fff', fontWeight: '600' },
  row: {
    padding: 14,
    backgroundColor: '#111',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#333',
  },
  rowText: { color: '#ddd' },
  empty: { color: '#888', textAlign: 'center', padding: 24 },
  swipeDelete: {
    backgroundColor: '#c0392b',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  swipeDeleteText: { color: '#fff', fontWeight: '600' },
  map: { height: 300 },
  videoRow: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    gap: 8,
    marginTop: 20,
    marginBottom: 20,
  },
  videoBox: { flex: 1 },
  videoLabel: { color: '#ddd', fontSize: 13, marginBottom: 4 },
  video: { height: 160, backgroundColor: '#000', borderRadius: 8 },
  qualityHeadline: {
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#2c2c2e',
  },
  qualityValue: {
    color: '#fff',
    fontSize: 26,
    fontWeight: '600',
    fontVariant: ['tabular-nums'],
  },
  qualityCaption: { color: '#8e8e93', fontSize: 11, marginTop: 4 },
  eventsCaveat: {
    color: '#777',
    fontSize: 11,
    lineHeight: 15,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  rawFallback: {
    color: '#999',
    fontFamily: 'Menlo',
    fontSize: 11,
    padding: 12,
  },
  closeButton: { padding: 16, alignItems: 'center' },
  closeText: { color: '#4a90d9', fontSize: 16 },
})
